# Production environment:
# - postgres: container
# - django: container
# - nginx: container
# - [react]: nginx

version: "3"

volumes:
  {{ cookiecutter.project_slug_snake_case }}_prod_postgres_data: {}
  {{ cookiecutter.project_slug_snake_case }}_prod_postgres_data_backups: {}

services:
  postgres:
    image: postgres:14.2
    container_name: {{ cookiecutter.project_slug_snake_case }}_prod_postgres
    volumes:
      - {{ cookiecutter.project_slug_snake_case }}_prod_postgres_data:/var/lib/postgresql/data:Z
      - {{ cookiecutter.project_slug_snake_case }}_prod_postgres_data_backups:/backups:z
    env_file:
      - ./server/.env.prod
    expose:
      - 5432

  django:
    build:
      context: .
      dockerfile: ./server/Dockerfile.prod
    image: {{ cookiecutter.project_slug_snake_case }}_prod_django
    platform: linux/amd64
    depends_on:
      - postgres
    env_file:
      - ./server/.env.prod
    command: bash -c "python /app/manage.py migrate && python /app/manage.py collectstatic --noinput && /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app"
    expose:
      - 5000:5000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: {{ cookiecutter.project_slug_snake_case }}_prod_nginx
    container_name: {{ cookiecutter.project_slug_snake_case }}_prod_nginx
    platform: linux/amd64
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # react?
