version: "3"

volumes:
  {{ cookiecutter.project_slug_snake_case }}_stage_postgres_data: {}
  {{ cookiecutter.project_slug_snake_case }}_stage_postgres_data_backups: {}

services:
  {{ cookiecutter.project_slug }}-django:
    build:
      context: .
      dockerfile: ./server/Dockerfile.stage
    image: {{ cookiecutter.project_slug_snake_case }}_stage_django
    container_name: {{ cookiecutter.project_slug_snake_case }}_stage_django
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - ./server:/app:z
    env_file:
      - ./server/.env.stage
    ports:
      - 8000:8000
      - 5000:5000 # VS Code debug server
    command: bash -c "python manage.py migrate && python manage.py runserver_plus --cert-file localhost 0.0.0.0:8000"

  postgres:
    image: postgres:14.2
    container_name: {{ cookiecutter.project_slug_snake_case }}_stage_postgres
    volumes:
      - {{ cookiecutter.project_slug_snake_case }}_stage_postgres_data:/var/lib/postgresql/data:Z
      - {{ cookiecutter.project_slug_snake_case }}_stage_postgres_data_backups:/backups:z
    env_file:
      - ./server/.env.stage
    expose:
      - 5432

