# stageuction environment:
# - postgres: container
# - django: container
# - nginx: container
# - [react]: nginx

version: "3"

volumes:
  {{ cookiecutter.project_slug_snake_case }}_stage_postgres_data: {}
  {{ cookiecutter.project_slug_snake_case }}_stage_postgres_data_backups: {}

services:
  postgres:
    image: postgres:14.2
    container_name: {{ cookiecutter.project_slug_snake_case }}_stage_postgres
    volumes:
      - {{ cookiecutter.project_slug_snake_case }}_stage_postgres_data:/var/lib/postgresql/data:Z
      - {{ cookiecutter.project_slug_snake_case }}_stage_postgres_data_backups:/backups:z
    env_file:
      - ./server/.env.stage
    expose:
      - 5432

  django:
    build:
      context: .
      dockerfile: ./server/Dockerfile.stage
    image: {{ cookiecutter.project_slug_snake_case }}_stage_django
    container_name: {{ cookiecutter.project_slug_snake_case }}_stage_django
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - ./server:/app:z
    env_file:
      - ./server/.env.stage
    expose:
      - 5000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver_plus 0.0.0.0:8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: {{ cookiecutter.project_slug_snake_case }}_stage_nginx
    container_name: {{ cookiecutter.project_slug_snake_case }}_stage_nginx
    platform: linux/amd64
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  # react?
